export const SET_BOARD = (state, name) => { state.board = name };
export const SET_SEARCH = (state, search) => { state.search = search };
export const SET_SECTIONS = (state, sections) => { state.sections = sections };
export const SET_TILES = (state, tiles) => { state.tiles = tiles };
export const SET_LABELS = (state, labels) => { state.labels = labels };
export const SET_SECTIONS1 = (state, sections) => { state.sections1 = sections };
export const SET_TILES1 = (state, tiles) => { state.tiles1 = tiles };
export const SET_LABELS1 = (state, labels) => { state.labels1 = labels };
export const SET_ZOOM = (state, zoom) => { state.zoom = zoom };